name: erp_farm
description: App Flutter para gestionar criaderos de animales.
publish_to: "none"
version: 0.0.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  intl: ^0.19.0
  path_provider: ^2.1.1
  share_plus: ^7.2.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.0.0
  package_info_plus: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets\\app_icon\\

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets\\app_icon\\icono_animalario.png"
  min_sdk_android: 21